-- 1. TABLAS PRINCIPALES
CREATE TABLE T_USER (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROL VARCHAR(20) DEFAULT 'Usuario'
);

CREATE TABLE T_USER_BITACORA (
    ID_BITACORA INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(255),
    USER_AUDITORIA VARCHAR(50),
    ACTION_AUDITORIA CHAR(1), -- 'A' (Alta), 'B' (Baja), 'C' (Cambio)
    FECHA_AUDITORIA DATETIME
);

-- 2. VISTA PARA LECTURA SEGURA
CREATE VIEW VIEW_USUARIOS AS
SELECT ID_USER, USERNAME, ROL 
FROM T_USER;

-- 3. TRIGGERS (Automatización de Auditoría)
DELIMITER //

CREATE TRIGGER TRG_AFTER_INSERT_USER
AFTER INSERT ON T_USER
FOR EACH ROW
BEGIN
    INSERT INTO T_USER_BITACORA (ID_USER, USERNAME, PASSWORD, USER_AUDITORIA, ACTION_AUDITORIA, FECHA_AUDITORIA)
    VALUES (NEW.ID_USER, NEW.USERNAME, NEW.PASSWORD, CURRENT_USER(), 'A', NOW());
END //

CREATE TRIGGER TRG_BEFORE_UPDATE_USER
BEFORE UPDATE ON T_USER
FOR EACH ROW
BEGIN
    INSERT INTO T_USER_BITACORA (ID_USER, USERNAME, PASSWORD, USER_AUDITORIA, ACTION_AUDITORIA, FECHA_AUDITORIA)
    VALUES (OLD.ID_USER, OLD.USERNAME, OLD.PASSWORD, CURRENT_USER(), 'C', NOW());
END //

CREATE TRIGGER TRG_BEFORE_DELETE_USER
BEFORE DELETE ON T_USER
FOR EACH ROW
BEGIN
    INSERT INTO T_USER_BITACORA (ID_USER, USERNAME, PASSWORD, USER_AUDITORIA, ACTION_AUDITORIA, FECHA_AUDITORIA)
    VALUES (OLD.ID_USER, OLD.USERNAME, OLD.PASSWORD, CURRENT_USER(), 'B', NOW());
END //

-- 4. STORED PROCEDURES (Únicos puntos de acceso)
CREATE PROCEDURE SP_A (IN p_username VARCHAR(50), IN p_password VARCHAR(255), IN p_rol VARCHAR(20))
BEGIN
    INSERT INTO T_USER (USERNAME, PASSWORD, ROL) VALUES (p_username, p_password, p_rol);
END //

CREATE PROCEDURE SP_C (IN p_id INT, IN p_username VARCHAR(50), IN p_password VARCHAR(255))
BEGIN
    UPDATE T_USER SET USERNAME = p_username, PASSWORD = p_password WHERE ID_USER = p_id;
END //

CREATE PROCEDURE SP_B (IN p_id INT)
BEGIN
    DELETE FROM T_USER WHERE ID_USER = p_id;
END //

CREATE PROCEDURE SP_CONSULTA ()
BEGIN
    SELECT * FROM VIEW_USUARIOS;
END //

DELIMITER ;