service: truequi-auth

useDotenv: true

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_NAME: ${env:DB_NAME}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:us-east-1:*:table/Usuarios"

functions:
  registroTradicional:
    handler: handler.registro_tradicional
    events:
      - http:
          path: /registro
          method: post
          cors: true
  loginGoogle:
    handler: handler.login_google
    events:
      - http:
          path: /login/google
          method: post
          cors: true
  loginTradicional:
    handler: handler.login_tradicional
    events:
      - http:
          path: /login
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  pythonRequirements: {}

package:
  patterns:
    - '!venv/**'
    - '!.serverless/**'